my_tools/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

#from quick_list import api, views
from quick_list import views



urlpatterns = patterns('',
    # Examples:
    url(r'^$', views.index, name='index'),
    url(r'^quick_list', include('quick_list.urls'), name='quick'),
    url(r'^quick_list_2', include('quick_list_2.urls'), name='quick_2'),
    # url(r'^grocery_list', include('grocery_list.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

quick_list/urls.py
from django.conf.urls import patterns, include, url
from quick_list import  views

urlpatterns = patterns('',
    url(r'^$', views.quick_list, name='quick_list'),
    
    url(r'^/(?P<list_id>[0-9]{1,5})/items$', views.quick_list_items, name='grocery_list_items'),
    # url(r'^/(?P<list_id>[0-9]{1,5})$', views.grocery_list, name='grocery_list'),
    
)

quick_list/models.py
import datetime
from django.db import models


class QuickListCategory(models.Model):
    category = models.CharField(max_length=30)

    def __unicode__(self):
        return u'{0}'.format(self.category)
    

class QuickList(models.Model):
    title = models.CharField(max_length=30)
    created_date = models.DateTimeField(
        null=True,
        blank=True,
        default=datetime.datetime.now
        )
    completed = models.BooleanField(default=False)

    def __unicode__(self):
        return u'{0}'.format(self.title)


class QuickListItem(models.Model):
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    quick_list = models.ForeignKey(QuickList, blank=True, null=True)
    category = models.ForeignKey(QuickListCategory, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=datetime.datetime.now)


    def __unicode__(self):
        return u'{0}'.format(self.name)

    # class Meta:
    #     unique_together = (("item", "grocery_list"),)

# class GroceryListTest(models.Model):
#     title = models.CharField(max_length=30)
#     created_date = models.DateTimeField(null=True, blank=True, default=datetime.datetime.now)
#     completed = models.BooleanField(default=False)
#     items = models.ManyToManyField(GroceryItem)

#     def __unicode__(self):
#         return u'{0}'.format(self.title)

quick_list/forms.py
from django.forms import ModelForm, TextInput
from quick_list import models

# class QuickListTestForm(ModelForm):

#     class Meta:
#         model = models.GroceryListTest
#         widgets = {
#             'title': TextInput(attrs={'placeholder': 'What would you like to name your list?'})
#         }

class QuickListForm(ModelForm):

    class Meta:
        model = models.QuickList
        widgets = {
            'title': TextInput(attrs={'placeholder': 'What would you like to name your list?'})
        }


class QuickListItemForm(ModelForm):

    class Meta:
        model = models.QuickListItem
        widgets = {
            'name': TextInput(attrs={'placeholder': 'Add List Item'})
        }

    # def clean_category(self):
    #     print "I need to clean the category"

quick_list/views.py
import json
from django.http import HttpResponse
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.views.generic import TemplateView
from django.http import QueryDict
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string


from quick_list import models, forms


def index(request):
    '''
    '''
    context = dict()
    quick_lists = models.QuickList.objects.all().select_related('item')
    
    context['quick_lists'] = quick_lists

    context['form'] = forms.QuickListForm()

    return render_to_response(
        'quick_list/quick_lists.html',
        context,
        context_instance=RequestContext(request)
    )



def quick_list(request, list_id=None):
    print "IN quick list"

    context = dict()
    if request.method == "POST":
        form = forms.QuickListForm(request.POST)
        if form.is_valid():
            print "Valid Form"
            gl, created = models.QuickList.objects.get_or_create(
                title=form.cleaned_data.get("title"))
            context['id'] = gl.id
            context['title'] = gl.title
            context['created_date'] = str(gl.created_date)
        else:
            print "invalid"
            context['errors'] = form.errors
            print form.errors

    elif request.method == "DELETE":
        print "Trying to delete"

    return HttpResponse(json.dumps(context), content_type="application/json")


def quick_list_items(request, list_id=None):
    """
    """
    print "IN items"
    context = dict()
    status = 200
    
    if request.method == "GET":
        print "Getting Items"
        context['quick_list'] = models.QuickList.objects.get(id=list_id)
        context['quick_list_items'] = models.QuickListItem.objects.filter(quick_list=list_id).order_by("-created_date")
        print context['quick_list']
        context['form'] = forms.QuickListItemForm()
        return render_to_response(
            'quick_list/quick_list_items.html',
            context,
            context_instance=RequestContext(request)
        )
        
    elif request.method == "POST":
        print request.POST
        form = forms.QuickListItemForm(request.POST)
        if form.is_valid():
            ql = models.QuickList.objects.get(id=list_id)

            i, ic = ql.quicklistitem_set.get_or_create(
                name=form.cleaned_data['name']
            )

            context['name'] = i.name
            context['category'] = i.category
            context['active'] = i.active
            context['id'] = i.id
            context['list_id'] = ql.id
            print context

        else:
            print "Not valid"
            status = 404
            print form.errors

        # item = models.GroceryItem.objects.get_or_create()

    elif request.method == "PUT":
        print "I am trying to update with a PUT"
        put = QueryDict(request.body)
        print put
        
        try:
            item = models.QuickListItem.objects.get(id=put.get("item_id"))
        except ObjectDoesNotExist:
            print "Dont' exists"
            item = None

        form = forms.QuickListItemForm(put, instance=item)
        if form.is_valid():
            print "PUT IS VALID"
            form.save()
            context['name'] = item.name
            # context['category'] = item.category
            context['active'] = item.active
            context['id'] = item.id
        else:
            status=404
            print form.errors

    elif request.method == "DELETE":
        print "Trying to delete"
        print request.body
        delete = QueryDict(request.body)
        gl = models.QuickList.objects.get(id=delete['quick_list']).delete()
        context['delete'] = "successful"
        # return redirect('/')


    # context['grocery_list'] = gl
    # context['form'] = forms.GroceryItemForm()

    return HttpResponse(json.dumps(context), status=status, content_type="application/json")

quick_list/templates/quick_list/base.html
 {% load staticfiles %}
<!doctype html>

<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Personal Assistant</title>
        <link rel="stylesheet" href="{% static "foundation-5.3.3/css/foundation.css" %}" />
        <link rel="stylesheet" href="{% static "js/jquery-ui-1.11.1.custom/jquery-ui.min.css" %}"></link>

        <script src="{% static "foundation-5.3.3/js/vendor/modernizr.js" %}"></script>
        <style>  
           /* .ng-invalid.ng-dirty {
                border-color: #FA787E;
            }
            .ng-valid.ng-dirty {
                border-color: #78FA89;
             }*/
             .list_item_delete{
              display: none;
             }
             #quick_list_form {
              display: none;
             }
            /* #new_item_form {
              display: none;
             }*/
        </style>
    </head>
    <body> 

<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <nav class="tab-bar">
      <section class="left-small">
        <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>

      <section class="middle tab-bar-section">
        <h1 class="title"></h1>
      </section>

<!--       <section class="right-small">
        <a class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section> -->
    </nav>

    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Main Menu</label></li>
        <li><a href="/">Quick List</a></li>
        <li><a href="/quick_list_2">Quick List V2</a></li>
        <li><a href="/">Media Center (Coming Soon)</a></li>
        <li><a href="/">Security Monitors (Coming Soon)</a></li>
        <li><a href="/">Placeholder 3</a></li>
      </ul>
    </aside>
<!-- 
    <aside class="right-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Users</label></li>
        <li><a href="#">Hari Seldon</a></li>
        <li><a href="#">...</a></li>
      </ul>
    </aside> -->

    <section class="main-section">
      <!-- content goes here -->
      {% csrf_token %}
      {% block content %}
      {% endblock %} 

    </section>

  <a class="exit-off-canvas"></a>

  </div>
</div>


    <script src="{% static "foundation-5.3.3/js/vendor/jquery.js" %}"></script>
    <script src="{% static "foundation-5.3.3/js/foundation.min.js" %}"></script>
    <script src="{% static "foundation-5.3.3/js/vendor/jquery.cookie.js" %}"></script>
    <script src="{% static "js/jquery-ui-1.11.1.custom/jquery-ui.min.js" %}"></script>
    <!-- // <script src="{% static "grocery_list/jquery.mobile-1.4.3/jquery.mobile-1.4.3.min.js" %}"></script> -->
    
    <script src="{% static "quick_list/app.js" %}"></script>

    <script>
      $(document).foundation();
    </script>
<script>
  $(function() {
    var availableTags = [
      "Apples",
      "Bananas",
      "Bacon",
      "Bread",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lettuce",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme",
      "Tomatoes"
    ];
    $( "#id_name" ).autocomplete({
      source: availableTags
    });
  });
  </script>
  </body>
</html>

quick_list/templates/quick_list/new_item_form.html
<!-- {{form.as_p}} -->


<form id="new_item_form">{% csrf_token %}
  <input id="id_quick_list" name="quick_list" type="hidden" value="{{quick_list.id}}">
  <div class="row">
    <div class="large-12 columns">
      <div class="row collapse">
        <div class="small-10 columns">
          {{form.name}}

        </div>
        <div class="small-2 columns">
          <a href="#" class="button postfix round">Add</a>
        </div>
      </div>
    </div>
  </div>
</form>



<!-- <div class="row">
  <div class="small-2 large-4 columns">x</div>
  <div class="small-4 large-4 columns">Bread</div>
  <div class="small-6 large-4 columns"><a href="#" class="close">&times;</a></div>
</div>
<div class="row">
  <div class="small-2 large-4 columns">x</div>
  <div class="small-4 large-4 columns">Bread</div>
  <div class="small-2 large-4 columns"><a href="#" class="close">&times;</a></div>
</div>
<div class="row">
  <div class="small-2 large-4 columns">x</div>
  <div class="small-4 large-4 columns">Bread</div>
  <div class="small-2 large-4 columns"><a href="#" class="close">&times;</a></div>
</div>
<div class="row">
  <div class="small-2 large-4 columns"><input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label></div>
  <div class="small-4 large-4 columns">Bread</div>
  <div class="small-2 large-4 columns"><a href="#" class="close">&times;</a></div>
</div> -->
<!-- <div data-alert class="alert-box alert round">
  This is an alert - alert that is rounded.
  <a href="#" class="close">&times;</a>
</div> -->
<!--   <div class="row">
    <div class="large-6 columns">
      <div class="row collapse prefix-round">
        <div class="small-3 columns">
          <a href="#" class="button prefix">Go</a>
        </div>
        <div class="small-9 columns">
          <input type="text" placeholder="Value">
        </div>
      </div>
    </div>
    <div class="large-6 columns">
      <div class="row collapse postfix-round">
        <div class="small-9 columns">
          <input type="text" placeholder="Value">
        </div>
        <div class="small-3 columns">
          <a href="#" class="button postfix">Go</a>
        </div>
      </div>
    </div>
  </div> -->

quick_list/templates/quick_list/quick_list_items.html
{% extends 'quick_list/base.html' %}

{% block content %}

<ul class="pricing-table">
  <li class="title">{{quick_list}}</li>
  <li class="price"></li>
  <li class="bullet-item">
      <div class="row list_filter_row">
        <div class="small-4 large-4 columns list_filter" id="all_selection"><h4><span class="header">All</span></h4></div>
        <div class="small-4 large-4 columns list_filter" id="active_selection"><h4><span class="subheader">Active</span></h4></div>
        <div class="small-4 large-4 columns list_filter" id="complete_selection"><h4><span class="subheader">Completed</span></h4></div>
      </div>
  </li>
  <div class="row"></div>
    {% include "quick_list/new_item_form.html" %}
</ul>


<ul class="pricing-table" id="item_ul">
    <!-- <li class="title"></li> -->
    <li class="price"></li>

    <!-- {# for i in grocery_list.groceryitem_set.all #} -->
    {% for i in quick_list_items %}
        <form class="exist_item_form">
            <input id="id_item_id" name="item_id" type="hidden" value="{{i.id}}">
            <input id="id_quick_list" name="quick_list" type="hidden" value="{{quick_list.id}}">
            <input id="id_name" name="name" type="hidden" value="{{i.name}}">
            <input id="id_active" name="active" type="hidden" value="{{i.active}}">
            {% if i.category %}
                <input id="id_category" name="category" type="hidden" 
                    value="{{i.category|default:None}}">
            {% endif %}
 
                <li {% if not i.active %} 
                        style="text-decoration: line-through" 
                    {% endif %}
                    class="bullet-item exist-item-link">
                    {% if i.active %}
                        <h4 class="header">{{i.name}}</h4>
                     {% else %}
                        <h4 class="subheader">{{i.name}}</h4>
                    {% endif %}

                 </li>
        </form>
   {% endfor %}
</ul>


<div class="panel clearfix">
    <a class="right nice small radius red button">Complete</a>
    <a href="/quick_list/{{quick_list.id}}/items" class="right nice small radius red button">Refresh</a>
    <form id="delete_list_form" method="POST">
        <input id="id_quick_list" name="quick_list" type="hidden" value="{{quick_list.id}}">
        <a href="/quick_list" class="delete_list_button left nice small radius red button">Delete Quick List</a>
    </form>
     
</div>

<a href="#" data-reveal-id="myModal">Click Me For A Modal</a>

<div id="myModal" class="reveal-modal" data-reveal>
  <h2>Awesome. I have it.</h2>
  <p class="lead">Your couch.  It is mine.</p>
  <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
  <a class="close-reveal-modal">&#215;</a>
</div>
{% endblock %}

quick_list/templates/quick_list/quick_list_new_form.html
  <div class="row">
    <div class="large-12 columns">
      <div class="row collapse">
        <div class="small-10 columns">
          {{form.title}}
        </div>
        <div class="small-2 columns">
          <a href="#" class="button postfix round">Add</a>
        </div>
      </div>
    </div>
  </div>

quick_list/templates/quick_list/quick_lists.html
{% extends 'quick_list/base.html' %}

{% block content %}

  <ul class="pricing-table" id="quick_list">
    <li class="title">Welcome {{name|default:" Guest!"}}</li>
      {% if quick_lists %}
        {% for l in quick_lists %}
          <li class="bullet-item quick_list_link">
            <a class="ui-link" href="/quick_list/{{l.id}}/items">
              <h5 class="subheader">{{ l.title }}</h5>
            </a>
          </li>
        {% endfor %}
      {% else %}
        <li class="bullet-item" id="no_list"> You don't have any lists yet. Lets get started.</li>
      {% endif %}
  </ul>


<form id="quick_list_form" method="POST">{% csrf_token %}
  {% include "quick_list/quick_list_new_form.html" %}
</form>

 <!-- Add a New List button -->
<div class="panel clearfix">
    <a href="/" class="button right">Refresh</a>
    
    <a href="#" class="add_new_quick_list_button button left">Add Quick List</a>
</div>


{% endblock %}
   